kl
kl

diff --git a/.github/workflows/tflint-checks copy.yml b/.github/workflows/tflint-checks copy.yml
--- a/.github/workflows/tflint-checks copy.yml
+++ b/.github/workflows/tflint-checks copy.yml
@@ -1,43 +1,36 @@
-name: terraform-infra-provisioning
+name: Terraform
+
 on:
-  workflow_dispatch:
-#  push:
-#    branches: [ '*' ]
-#    paths-ignore:
-#      - '**/README.md'
   pull_request:
-    branches: ["main"]
-    paths-ignore:
-      - '**/README.md'
+    branches:
+      - master
+  push:
+    branches:
+      - master
+
 env:
   tf_version: '1.5.7'
   tg_version: '0.53.2'
   tg_dir: './'
   
-permissions: read-all
-#--------------------------
-#
-# PLEASE READ: Add a GitHub Actions variable 'INFRACOST_SCAN_TYPE' and set the value to either 'hcl_code' or 'tf_plan' depending on what type of Infracost scan desired.
-#
-#--------------------------
 jobs:
   terraform:
-    name: 'continuous-integration'
-    runs-on: ubuntu-latest
-    environment: production
-    permissions:
-      contents: read
-      id-token: write
-      pull-requests: write
-    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+    name: Plan / Apply
+    runs-on: ubuntu-20.04
     defaults:
       run:
-        shell: bash
-
+        working-directory: terraform
+    permissions:
+      contents: read
+      pull-requests: write
     steps:
-    # Checkout the repository to the GitHub Actions runner
     - name: Checkout
-      uses: actions/checkout@v3
+      uses: actions/checkout@v2
+
+    - name: Use Terraform 1.3.7
+      uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_version: 1.3.7
 
     # Terragrunt Check
     - name: Terraform Format
@@ -50,105 +43,80 @@ jobs:
           tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
       continue-on-error: true
 
-#    - name: Setup Infracost
-#      uses: infracost/actions/setup@v2
-#      # See https://github.com/infracost/actions/tree/master/setup for other inputs
-#      # If you can't use this action, see Docker images in https://infracost.io/cicd
-#      with:
-#        api-key: ${{ secrets.INFRACOST_API_KEY }}
-#      if: github.event_name == 'pull_request'
-#      continue-on-error: true
+    - name: Terraform Init
+      id: init
+      run: terraform init
+      continue-on-error: true
 
-      # Checkout the base branch of the pull request (e.g. main/master).
-#    - name: Checkout base branch
-#      if: ${{ (github.event_name == 'pull_request') && (vars.INFRACOST_SCAN_TYPE  == 'hcl_code') }}
-#      uses: actions/checkout@v3
-#      with:
-#        ref: '${{ github.event.pull_request.base.ref }}'
-#      continue-on-error: true
+    - name: Terraform Validate
+      id: validate
+      run: terraform validate -no-color
+      continue-on-error: true
 
-    # Generate Infracost JSON file as the baseline.
-#    - name: Generate Infracost cost estimate baseline
-#      if: ${{ (github.event_name == 'pull_request') && (vars.INFRACOST_SCAN_TYPE  == 'hcl_code') }}
-#      run: |
-#        infracost breakdown --path=. \
-#                            --format=json \
-#                            --out-file=/tmp/infracost-base.json
-#      continue-on-error: true
+    - name: Terraform Plan
+      id: plan
+      if: github.event_name == 'pull_request'
+      run: terraform plan -no-color -input=false
+      continue-on-error: true
 
-    # Checkout the current PR branch so we can create a diff.
-#    - name: Checkout PR branch
-#      if: ${{ (github.event_name == 'pull_request') && (vars.INFRACOST_SCAN_TYPE  == 'hcl_code') }}
-#      uses: actions/checkout@v3
-#      continue-on-error: true
-
-    # Generate an Infracost diff and save it to a JSON file.
-#    - name: Generate Infracost diff
-#      if: ${{ (github.event_name == 'pull_request') && (vars.INFRACOST_SCAN_TYPE  == 'hcl_code') }}
-#      run: |
-#        infracost diff --path=. \
-#                        --format=json \
-#                        --compare-to=/tmp/infracost-base.json \
-#                        --out-file=/tmp/infracost.json
-#      continue-on-error: true
-
-    # Checks that all Terraform configuration files are correctly written
-#    - name: Terraform Validate
-#      id: validate
-#      run: terraform validate -no-color
-    # Generates an execution plan for Terraform
-#    - name: Terraform Plan
-#      id: plan
-#      if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
-#      run: |
-#        terraform plan -no-color -input=false \
-#        -out=TFplan.JSON
-#      continue-on-error: true
-
-    # Generate an Infracost diff and save it to a JSON file.
-#    - name: Generate Infracost diff
-#      if:  ${{ (github.event_name == 'pull_request') && (vars.INFRACOST_SCAN_TYPE  == 'tf_plan') }}
-#      run: |
-#        infracost diff --path=TFplan.JSON \
-#                        --format=json \
-#                        --out-file=/tmp/infracost.json
-#      continue-on-error: true
-
-#    - name: Post Infracost estimate
-#      if: github.event_name == 'pull_request'
-#      run: |
-#          infracost comment github --path=/tmp/infracost.json \
-#                                    --repo=$GITHUB_REPOSITORY \
-#                                    --github-token=${{github.token}} \
-#                                    --pull-request=${{github.event.pull_request.number}} \
-#                                    --show-skipped \
-#                                    --behavior=update
-#      continue-on-error: true
-
-    - name: Post Terraform Plan output
+    - name: Pull Request Comment
       uses: actions/github-script@v6
+      if: github.event_name == 'pull_request'
+      env:
+        PLAN: "${{ steps.plan.outputs.stdout }}"
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
-          const output = `#### Terraform Format and Style 🖌\`toJSON(${{ steps }})\`
-
-          <details><summary>Show Plan</summary>
-          \`\`\`\n
-          TEST
-          \`\`\`
-          </details>
-
-          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
+          const { data: comments } = await github.rest.issues.listComments({
             owner: context.repo.owner,
             repo: context.repo.repo,
-            body: output
+            issue_number: context.issue.number,
           })
-      
-    # On push to "main", build or change infrastructure according to Terraform configuration files
-    # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+          const botComment = comments.find(comment => {
+            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
+          })
+
+          const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
+          #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
+          #### Terraform Validation 🤖 \`${{ steps.validate.outcome }}\`
+          <details><summary>Validation Output</summary>
+
+          \`\`\`\n
+          ${{ steps.validate.outputs.stdout }}
+          \`\`\`
+
+          </details>
+
+          #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
+
+          <details><summary>Show Plan</summary>
+
+          \`\`\`terraform\n
+          ${process.env.PLAN}
+          \`\`\`
+
+          </details>`;
+
+          if (botComment) {
+            github.rest.issues.updateComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              comment_id: botComment.id,
+              body: output
+            })
+          } else {
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
+          }
+
+#    - name: Terraform Status
+#      if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure'
+#      run: exit 1
+#
 #    - name: Terraform Apply
-#      if: github.ref == 'refs/heads/main'
+#      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
 #      run: terraform apply -auto-approve -input=false
