hgvg
,j

diff --git a/.github/workflows/tflint-checks.yml b/.github/workflows/tflint-checks.yml
--- a/.github/workflows/tflint-checks.yml
+++ b/.github/workflows/tflint-checks.yml
@@ -9,6 +9,8 @@ env:
 jobs:
   checks:
     runs-on: ubuntu-latest
+    outputs:
+      CHECK_STATUS: "${{ env.CHECK_STATUS }}"
     strategy:
       fail-fast: false
       matrix:
@@ -17,26 +19,34 @@ jobs:
           - prod
 
     steps:
-      - name: 'Checkout'
-        uses: actions/checkout@main
-
-      - name: Check terragrunt HCL
-        uses: gruntwork-io/terragrunt-action@v2
+      - uses: actions/checkout@v3
         with:
-          tf_version: ${{ env.tf_version }}
-          tg_version: ${{ env.tg_version }}
-          tg_dir: environment/${{ matrix.path }}
-          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
-
-      - name: Add & Commit
-        uses: EndBug/add-and-commit@v5.1.0
+          fetch-depth: 2
+      - name: Fetch changed files
+        id: pr_files
+        uses: jitterbit/get-changed-files@v1
         with:
-          add: '.'
-          author_name: 'Jake Jones - ' ${{ matrix.path }}
-          author_email: ''
-          branch: ''
-          cwd: ''
-          message: 'ran terraform fmt'
-          remove: ''
-          signoff: ''
-          tag: ''
+          format: 'space-delimited'
+
+      - name: Validate terraform fmt (added_modified)
+        run: |
+          set +e
+
+          echo "CHECK_STATUS=0" >> $GITHUB_ENV
+
+          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
+            echo "Checking terraform fmt on ${changed_file}..."
+
+            if [[ $changed_file == *.hcl ]]; then
+              terragrunt hclfmt --terragrunt-hclfmt-file $changed_file
+              FMT_STATUS=$(echo $?)
+
+              if [[ $FMT_STATUS -ne 0 ]]; then
+                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
+                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+              fi
+            fi
+          done
+      - name: Process check
+        if: always()
+        run: exit $CHECK_STATUS
